# MobileNetV3-Small Configuration
# Fastest inference, good for deployment

data_dir: data/raw/bloodmnist
output_dir: models/bloodmnist_mobilenet

backbone: mobilenet_v3_small
num_classes: 8
pretrained: true
freeze_backbone: false

epochs: 30
batch_size: 32
accumulation_steps: 1
lr: 0.0001
weight_decay: 0.0001
optimizer: adamw
scheduler: cosine

img_size: 224
num_workers: 2
use_class_weights: true
use_albumentations: false

use_amp: true
seed: 42
