# BloodMNIST Training Configuration
# Lightweight model for Mac M2 8GB RAM

# Data configuration
data_dir: data/raw/bloodmnist
output_dir: models/bloodmnist_efficientnet

# Model configuration
backbone: efficientnet_lite0
num_classes: 8
pretrained: true
freeze_backbone: true
unfreeze_after: 3

# Training configuration
epochs: 25
batch_size: 16
accumulation_steps: 2
lr: 0.0001
weight_decay: 0.0001
optimizer: adamw
scheduler: cosine

# Data configuration
img_size: 224
num_workers: 2
use_class_weights: true
use_albumentations: false

# Other settings
use_amp: true
seed: 42

# Notes:
# - Batch size 16 with accumulation_steps 2 = effective batch size 32
# - Freeze backbone for first 3 epochs, then fine-tune with lower LR
# - Expected training time: ~30-40 minutes on M2
# - Expected validation accuracy: >95%
